### ISSUE TITLE
using output in toolbox as [Create Temporary Layer] issues

### ISSUE THREAD

**Issue by okanisis** [tsw-apropos/qmarxantoolbox#2]
I noticed, at least for the "Create Planning Unit Layer" tool that when you set the output to [Create Temporary Layer] it does a few things that could use some fixing.

1.) It creates a file in the users /home folder (normally these are placed in memory and for linux that is in /tmp/processingXXXXXXXX/memory.shp

2.) It's named memory:.shp (notice the funny colon!)

3.) The layer has to be manually added to the canvas as it isn't automatically after running the tool.

This is on QGIS 2.18.9 64-bit Linux.

**Comment by aproposinfosystems** [comment]
The use of the temporary layer is not recommended practice for this tool. Layers should be saved as shapefiles. The Toolbox api does not provide a way of limiting output options. I will look at improving messaging around this issue in a future release.
