### ISSUE TITLE
Mini dump

### ISSUE THREAD

**Issue by mfarigoule** [tsw-apropos/qmarxantoolbox#3]
Hello, 

When i use Qmarxan (Points in Planning Units), each time, i have a mini dump with this message : 
![image](https://user-images.githubusercontent.com/50320865/57216766-19132f80-6ff1-11e9-9047-c9793d10e122.png)
It writes the file but it dumps every time. I tried with my boss computer and it works ... 
Can you help me ? 
Thanks !

**Comment by aproposinfosystems** [comment]
Points in Planning Units is not part of the QMarxan Toolbox. This is part of the old QMarxan and is no longer supported. Please upgrade to QGIS 3.x and use the new tool.
